import type { Habit, TVMProjection } from '@/types';

/**
 * Calculate the Future Value of a series of equal periodic payments (annuity).
 *
 * FV = PMT × [((1 + r)^n − 1) / r]
 *
 * @param monthlyPayment  Amount invested each month (PMT)
 * @param annualRate      Annual interest rate as a decimal (e.g. 0.07 for 7%)
 * @param years           Investment horizon in years
 * @returns Future value in dollars
 */
export function futureValueAnnuity(
  monthlyPayment: number,
  annualRate: number,
  years: number
): number {
  if (monthlyPayment <= 0 || annualRate < 0 || years <= 0) return 0;

  const monthlyRate = annualRate / 12;
  const periods = years * 12;

  if (monthlyRate === 0) {
    return monthlyPayment * periods;
  }

  return monthlyPayment * ((Math.pow(1 + monthlyRate, periods) - 1) / monthlyRate);
}

/**
 * Build a full TVM projection object for display.
 */
export function buildTVMProjection(
  monthlyAmount: number,
  annualRate: number,
  years: number
): TVMProjection {
  const futureValue = futureValueAnnuity(monthlyAmount, annualRate, years);
  const totalContributions = monthlyAmount * 12 * years;
  return {
    years,
    futureValue,
    totalContributions,
    totalGrowth: futureValue - totalContributions,
    monthlyAmount,
    annualRate,
  };
}

/**
 * Calculate the approximate monthly savings generated by a habit
 * (based on average historical spending on that habit per month).
 *
 * If habit has no spend data yet, falls back to a user-provided estimate.
 */
export function monthlyHabitSavings(habit: Habit, estimatedMonthlySpend?: number): number {
  if (habit.totalSpent > 0) {
    // Approximate months active
    const createdAt = new Date(habit.createdAt);
    const now = new Date();
    const monthsActive = Math.max(
      1,
      (now.getFullYear() - createdAt.getFullYear()) * 12 +
        (now.getMonth() - createdAt.getMonth())
    );
    return habit.totalSpent / monthsActive;
  }
  return estimatedMonthlySpend ?? 0;
}

/**
 * Sum the estimated monthly savings across all active habits.
 */
export function calculateTotalMonthlySavings(habits: Habit[]): number {
  return habits
    .filter((h) => h.isActive)
    .reduce((sum, h) => sum + monthlyHabitSavings(h), 0);
}

/**
 * How much a single daily expenditure compounds to over N years.
 * Convenience wrapper for the "coffee math" insight cards.
 */
export function dailySpendToFutureValue(
  dailyAmount: number,
  annualRate: number,
  years: number
): number {
  const monthlyAmount = dailyAmount * (365 / 12);
  return futureValueAnnuity(monthlyAmount, annualRate, years);
}

/**
 * Calculate pledge amount from a transaction.
 */
export function calculatePledgeAmount(
  transactionAmount: number,
  pledgeType: 'percentage' | 'fixed',
  pledgeAmount: number
): number {
  if (pledgeType === 'percentage') {
    return Math.round(transactionAmount * (pledgeAmount / 100) * 100) / 100;
  }
  return pledgeAmount;
}

/**
 * Format a rate as a percentage string.
 */
export function formatRate(rate: number): string {
  return `${(rate * 100).toFixed(1)}%`;
}

/**
 * Generate a series of year-by-year projections for a chart.
 */
export function yearlyProjections(
  monthlyAmount: number,
  annualRate: number,
  maxYears: number
): Array<{ year: number; value: number; contributions: number }> {
  return Array.from({ length: maxYears }, (_, i) => {
    const year = i + 1;
    return {
      year,
      value: Math.round(futureValueAnnuity(monthlyAmount, annualRate, year)),
      contributions: Math.round(monthlyAmount * 12 * year),
    };
  });
}
